/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConformiteRouteImport } from './routes/conformite'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EspacePatientRouteImport } from './routes/espace-patient'
import { Route as MonEspaceRouteImport } from './routes/mon-espace'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as MonEspaceIndexRouteImport } from './routes/mon-espace.index'
import { Route as MonEspaceMessagesRouteImport } from './routes/mon-espace.messages'
import { Route as MonEspaceProfilRouteImport } from './routes/mon-espace.profil'
import { Route as MonEspaceSuiviRouteImport } from './routes/mon-espace.suivi'
import { Route as QuestionnaireIndexRouteImport } from './routes/questionnaire.index'
import { Route as QuestionnaireSlugRouteImport } from './routes/questionnaire.$slug'
import { Route as SoinsDomaineRouteImport } from './routes/soins.$domaine'
import { Route as MonEspaceSoinsIndexRouteImport } from './routes/mon-espace.soins.index'
import { Route as MonEspaceSoinsJourneyIdRouteImport } from './routes/mon-espace.soins.$journeyId'
import { Route as SoinsDomaineProduitRouteImport } from './routes/soins.$domaine_.$produit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformiteRoute = ConformiteRouteImport.update({
  id: '/conformite',
  path: '/conformite',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacePatientRoute = EspacePatientRouteImport.update({
  id: '/espace-patient',
  path: '/espace-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEspaceRoute = MonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEspaceIndexRoute = MonEspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MonEspaceRoute,
} as any)
const MonEspaceMessagesRoute = MonEspaceMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MonEspaceRoute,
} as any)
const MonEspaceProfilRoute = MonEspaceProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => MonEspaceRoute,
} as any)
const MonEspaceSuiviRoute = MonEspaceSuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => MonEspaceRoute,
} as any)
const QuestionnaireIndexRoute = QuestionnaireIndexRouteImport.update({
  id: '/questionnaire/',
  path: '/questionnaire/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireSlugRoute = QuestionnaireSlugRouteImport.update({
  id: '/questionnaire/$slug',
  path: '/questionnaire/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsDomaineRoute = SoinsDomaineRouteImport.update({
  id: '/soins/$domaine',
  path: '/soins/$domaine',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEspaceSoinsIndexRoute = MonEspaceSoinsIndexRouteImport.update({
  id: '/soins/',
  path: '/soins/',
  getParentRoute: () => MonEspaceRoute,
} as any)
const MonEspaceSoinsJourneyIdRoute = MonEspaceSoinsJourneyIdRouteImport.update({
  id: '/soins/$journeyId',
  path: '/soins/$journeyId',
  getParentRoute: () => MonEspaceRoute,
} as any)
const SoinsDomaineProduitRoute = SoinsDomaineProduitRouteImport.update({
  id: '/soins/$domaine_/$produit',
  path: '/soins/$domaine/$produit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conformite': typeof ConformiteRoute
  '/cookies': typeof CookiesRoute
  '/espace-patient': typeof EspacePatientRoute
  '/mon-espace': typeof MonEspaceRouteWithChildren
  '/parcours': typeof ParcoursRoute
  '/statistiques': typeof StatistiquesRoute
  '/mon-espace/messages': typeof MonEspaceMessagesRoute
  '/mon-espace/profil': typeof MonEspaceProfilRoute
  '/mon-espace/suivi': typeof MonEspaceSuiviRoute
  '/questionnaire/$slug': typeof QuestionnaireSlugRoute
  '/soins/$domaine': typeof SoinsDomaineRoute
  '/mon-espace/': typeof MonEspaceIndexRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/mon-espace/soins/$journeyId': typeof MonEspaceSoinsJourneyIdRoute
  '/soins/$domaine/$produit': typeof SoinsDomaineProduitRoute
  '/mon-espace/soins/': typeof MonEspaceSoinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conformite': typeof ConformiteRoute
  '/cookies': typeof CookiesRoute
  '/espace-patient': typeof EspacePatientRoute
  '/parcours': typeof ParcoursRoute
  '/statistiques': typeof StatistiquesRoute
  '/mon-espace/messages': typeof MonEspaceMessagesRoute
  '/mon-espace/profil': typeof MonEspaceProfilRoute
  '/mon-espace/suivi': typeof MonEspaceSuiviRoute
  '/questionnaire/$slug': typeof QuestionnaireSlugRoute
  '/soins/$domaine': typeof SoinsDomaineRoute
  '/mon-espace': typeof MonEspaceIndexRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/mon-espace/soins/$journeyId': typeof MonEspaceSoinsJourneyIdRoute
  '/soins/$domaine/$produit': typeof SoinsDomaineProduitRoute
  '/mon-espace/soins': typeof MonEspaceSoinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conformite': typeof ConformiteRoute
  '/cookies': typeof CookiesRoute
  '/espace-patient': typeof EspacePatientRoute
  '/mon-espace': typeof MonEspaceRouteWithChildren
  '/parcours': typeof ParcoursRoute
  '/statistiques': typeof StatistiquesRoute
  '/mon-espace/messages': typeof MonEspaceMessagesRoute
  '/mon-espace/profil': typeof MonEspaceProfilRoute
  '/mon-espace/suivi': typeof MonEspaceSuiviRoute
  '/questionnaire/$slug': typeof QuestionnaireSlugRoute
  '/soins/$domaine': typeof SoinsDomaineRoute
  '/mon-espace/': typeof MonEspaceIndexRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/mon-espace/soins/$journeyId': typeof MonEspaceSoinsJourneyIdRoute
  '/soins/$domaine_/$produit': typeof SoinsDomaineProduitRoute
  '/mon-espace/soins/': typeof MonEspaceSoinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/conformite'
    | '/cookies'
    | '/espace-patient'
    | '/mon-espace'
    | '/parcours'
    | '/statistiques'
    | '/mon-espace/messages'
    | '/mon-espace/profil'
    | '/mon-espace/suivi'
    | '/questionnaire/$slug'
    | '/soins/$domaine'
    | '/mon-espace/'
    | '/questionnaire/'
    | '/mon-espace/soins/$journeyId'
    | '/soins/$domaine/$produit'
    | '/mon-espace/soins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/conformite'
    | '/cookies'
    | '/espace-patient'
    | '/parcours'
    | '/statistiques'
    | '/mon-espace/messages'
    | '/mon-espace/profil'
    | '/mon-espace/suivi'
    | '/questionnaire/$slug'
    | '/soins/$domaine'
    | '/mon-espace'
    | '/questionnaire'
    | '/mon-espace/soins/$journeyId'
    | '/soins/$domaine/$produit'
    | '/mon-espace/soins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/conformite'
    | '/cookies'
    | '/espace-patient'
    | '/mon-espace'
    | '/parcours'
    | '/statistiques'
    | '/mon-espace/messages'
    | '/mon-espace/profil'
    | '/mon-espace/suivi'
    | '/questionnaire/$slug'
    | '/soins/$domaine'
    | '/mon-espace/'
    | '/questionnaire/'
    | '/mon-espace/soins/$journeyId'
    | '/soins/$domaine_/$produit'
    | '/mon-espace/soins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConformiteRoute: typeof ConformiteRoute
  CookiesRoute: typeof CookiesRoute
  EspacePatientRoute: typeof EspacePatientRoute
  MonEspaceRoute: typeof MonEspaceRouteWithChildren
  ParcoursRoute: typeof ParcoursRoute
  StatistiquesRoute: typeof StatistiquesRoute
  QuestionnaireSlugRoute: typeof QuestionnaireSlugRoute
  SoinsDomaineRoute: typeof SoinsDomaineRoute
  QuestionnaireIndexRoute: typeof QuestionnaireIndexRoute
  SoinsDomaineProduitRoute: typeof SoinsDomaineProduitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformite': {
      id: '/conformite'
      path: '/conformite'
      fullPath: '/conformite'
      preLoaderRoute: typeof ConformiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-patient': {
      id: '/espace-patient'
      path: '/espace-patient'
      fullPath: '/espace-patient'
      preLoaderRoute: typeof EspacePatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-espace': {
      id: '/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof MonEspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-espace/': {
      id: '/mon-espace/'
      path: '/'
      fullPath: '/mon-espace/'
      preLoaderRoute: typeof MonEspaceIndexRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/mon-espace/messages': {
      id: '/mon-espace/messages'
      path: '/messages'
      fullPath: '/mon-espace/messages'
      preLoaderRoute: typeof MonEspaceMessagesRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/mon-espace/profil': {
      id: '/mon-espace/profil'
      path: '/profil'
      fullPath: '/mon-espace/profil'
      preLoaderRoute: typeof MonEspaceProfilRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/mon-espace/suivi': {
      id: '/mon-espace/suivi'
      path: '/suivi'
      fullPath: '/mon-espace/suivi'
      preLoaderRoute: typeof MonEspaceSuiviRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/questionnaire/': {
      id: '/questionnaire/'
      path: '/questionnaire'
      fullPath: '/questionnaire/'
      preLoaderRoute: typeof QuestionnaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/$slug': {
      id: '/questionnaire/$slug'
      path: '/questionnaire/$slug'
      fullPath: '/questionnaire/$slug'
      preLoaderRoute: typeof QuestionnaireSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins/$domaine': {
      id: '/soins/$domaine'
      path: '/soins/$domaine'
      fullPath: '/soins/$domaine'
      preLoaderRoute: typeof SoinsDomaineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-espace/soins/': {
      id: '/mon-espace/soins/'
      path: '/soins'
      fullPath: '/mon-espace/soins/'
      preLoaderRoute: typeof MonEspaceSoinsIndexRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/mon-espace/soins/$journeyId': {
      id: '/mon-espace/soins/$journeyId'
      path: '/soins/$journeyId'
      fullPath: '/mon-espace/soins/$journeyId'
      preLoaderRoute: typeof MonEspaceSoinsJourneyIdRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/soins/$domaine_/$produit': {
      id: '/soins/$domaine_/$produit'
      path: '/soins/$domaine/$produit'
      fullPath: '/soins/$domaine/$produit'
      preLoaderRoute: typeof SoinsDomaineProduitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MonEspaceRouteChildren {
  MonEspaceMessagesRoute: typeof MonEspaceMessagesRoute
  MonEspaceProfilRoute: typeof MonEspaceProfilRoute
  MonEspaceSuiviRoute: typeof MonEspaceSuiviRoute
  MonEspaceIndexRoute: typeof MonEspaceIndexRoute
  MonEspaceSoinsJourneyIdRoute: typeof MonEspaceSoinsJourneyIdRoute
  MonEspaceSoinsIndexRoute: typeof MonEspaceSoinsIndexRoute
}

const MonEspaceRouteChildren: MonEspaceRouteChildren = {
  MonEspaceMessagesRoute: MonEspaceMessagesRoute,
  MonEspaceProfilRoute: MonEspaceProfilRoute,
  MonEspaceSuiviRoute: MonEspaceSuiviRoute,
  MonEspaceIndexRoute: MonEspaceIndexRoute,
  MonEspaceSoinsJourneyIdRoute: MonEspaceSoinsJourneyIdRoute,
  MonEspaceSoinsIndexRoute: MonEspaceSoinsIndexRoute,
}

const MonEspaceRouteWithChildren = MonEspaceRoute._addFileChildren(
  MonEspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConformiteRoute: ConformiteRoute,
  CookiesRoute: CookiesRoute,
  EspacePatientRoute: EspacePatientRoute,
  MonEspaceRoute: MonEspaceRouteWithChildren,
  ParcoursRoute: ParcoursRoute,
  StatistiquesRoute: StatistiquesRoute,
  QuestionnaireSlugRoute: QuestionnaireSlugRoute,
  SoinsDomaineRoute: SoinsDomaineRoute,
  QuestionnaireIndexRoute: QuestionnaireIndexRoute,
  SoinsDomaineProduitRoute: SoinsDomaineProduitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
