/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConformiteRouteImport } from './routes/conformite'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EspacePatientRouteImport } from './routes/espace-patient'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as QuestionnaireIndexRouteImport } from './routes/questionnaire.index'
import { Route as QuestionnaireSlugRouteImport } from './routes/questionnaire.$slug'
import { Route as SoinsIndexRouteImport } from './routes/soins.index'
import { Route as SoinsDomaineRouteImport } from './routes/soins.$domaine'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformiteRoute = ConformiteRouteImport.update({
  id: '/conformite',
  path: '/conformite',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EspacePatientRoute = EspacePatientRouteImport.update({
  id: '/espace-patient',
  path: '/espace-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireIndexRoute = QuestionnaireIndexRouteImport.update({
  id: '/questionnaire/',
  path: '/questionnaire/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireSlugRoute = QuestionnaireSlugRouteImport.update({
  id: '/questionnaire/$slug',
  path: '/questionnaire/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsIndexRoute = SoinsIndexRouteImport.update({
  id: '/soins/',
  path: '/soins/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsDomaineRoute = SoinsDomaineRouteImport.update({
  id: '/soins/$domaine',
  path: '/soins/$domaine',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conformite': typeof ConformiteRoute
  '/cookies': typeof CookiesRoute
  '/espace-patient': typeof EspacePatientRoute
  '/parcours': typeof ParcoursRoute
  '/statistiques': typeof StatistiquesRoute
  '/questionnaire/$slug': typeof QuestionnaireSlugRoute
  '/soins/$domaine': typeof SoinsDomaineRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/soins/': typeof SoinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conformite': typeof ConformiteRoute
  '/cookies': typeof CookiesRoute
  '/espace-patient': typeof EspacePatientRoute
  '/parcours': typeof ParcoursRoute
  '/statistiques': typeof StatistiquesRoute
  '/questionnaire/$slug': typeof QuestionnaireSlugRoute
  '/soins/$domaine': typeof SoinsDomaineRoute
  '/questionnaire': typeof QuestionnaireIndexRoute
  '/soins': typeof SoinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conformite': typeof ConformiteRoute
  '/cookies': typeof CookiesRoute
  '/espace-patient': typeof EspacePatientRoute
  '/parcours': typeof ParcoursRoute
  '/statistiques': typeof StatistiquesRoute
  '/questionnaire/$slug': typeof QuestionnaireSlugRoute
  '/soins/$domaine': typeof SoinsDomaineRoute
  '/questionnaire/': typeof QuestionnaireIndexRoute
  '/soins/': typeof SoinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/conformite'
    | '/cookies'
    | '/espace-patient'
    | '/parcours'
    | '/statistiques'
    | '/questionnaire/$slug'
    | '/soins/$domaine'
    | '/questionnaire/'
    | '/soins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/conformite'
    | '/cookies'
    | '/espace-patient'
    | '/parcours'
    | '/statistiques'
    | '/questionnaire/$slug'
    | '/soins/$domaine'
    | '/questionnaire'
    | '/soins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/conformite'
    | '/cookies'
    | '/espace-patient'
    | '/parcours'
    | '/statistiques'
    | '/questionnaire/$slug'
    | '/soins/$domaine'
    | '/questionnaire/'
    | '/soins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConformiteRoute: typeof ConformiteRoute
  CookiesRoute: typeof CookiesRoute
  EspacePatientRoute: typeof EspacePatientRoute
  ParcoursRoute: typeof ParcoursRoute
  StatistiquesRoute: typeof StatistiquesRoute
  QuestionnaireSlugRoute: typeof QuestionnaireSlugRoute
  SoinsDomaineRoute: typeof SoinsDomaineRoute
  QuestionnaireIndexRoute: typeof QuestionnaireIndexRoute
  SoinsIndexRoute: typeof SoinsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformite': {
      id: '/conformite'
      path: '/conformite'
      fullPath: '/conformite'
      preLoaderRoute: typeof ConformiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-patient': {
      id: '/espace-patient'
      path: '/espace-patient'
      fullPath: '/espace-patient'
      preLoaderRoute: typeof EspacePatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/': {
      id: '/questionnaire/'
      path: '/questionnaire'
      fullPath: '/questionnaire/'
      preLoaderRoute: typeof QuestionnaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/$slug': {
      id: '/questionnaire/$slug'
      path: '/questionnaire/$slug'
      fullPath: '/questionnaire/$slug'
      preLoaderRoute: typeof QuestionnaireSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins/': {
      id: '/soins/'
      path: '/soins'
      fullPath: '/soins/'
      preLoaderRoute: typeof SoinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins/$domaine': {
      id: '/soins/$domaine'
      path: '/soins/$domaine'
      fullPath: '/soins/$domaine'
      preLoaderRoute: typeof SoinsDomaineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConformiteRoute: ConformiteRoute,
  CookiesRoute: CookiesRoute,
  EspacePatientRoute: EspacePatientRoute,
  ParcoursRoute: ParcoursRoute,
  StatistiquesRoute: StatistiquesRoute,
  QuestionnaireSlugRoute: QuestionnaireSlugRoute,
  SoinsDomaineRoute: SoinsDomaineRoute,
  QuestionnaireIndexRoute: QuestionnaireIndexRoute,
  SoinsIndexRoute: SoinsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
